// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package model.domain;

import model.domain.Ejecucion;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Ejecucion_Roo_Configurable {
    
    declare @type: Ejecucion: @Configurable;
    
}
