// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package model.domain;

import model.domain.Direccion;

privileged aspect Direccion_Roo_JavaBean {
    
    public String Direccion.getDescripcion() {
        return this.descripcion;
    }
    
    public void Direccion.setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
}
