// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package model.domain;

import model.domain.Operario;

privileged aspect Operario_Roo_JavaBean {
    
    public String Operario.getNombre() {
        return this.nombre;
    }
    
    public void Operario.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
